version: 0.2
env:
  variables:
    VERSION: 1.0.0
    STACK_NAME: s3-testing
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - aws cloudformation package --template ${CODEBUILD_SRC_DIR}/ops/stack.yaml --s3-bucket cf-notify-eil4t > deployme.yaml
      - sed -i -e '1d' deployme.yaml 
